### ISSUE TITLE
Restyle the Group Configuration page

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/Mouser#189]
**Describe the feature that you would like added**
The styling of the Group Configuration page is very outdated, so it needs to be restyled

**Tasks that need to completed for this feature**
- [ ] Remove the calendar dropdown menu
- [ ] Get rid of the background colors on each of the groups (they are currently green and blue)
- [ ] Properly space the "Animal ID" and "Weight" labels (there is no spacing between the two, and they go down too far if there are no animals within a specific cage)
- [ ] Extend everything further horizontally (there is a lot of whitespace to the right)
- [ ] If possible, find a way to remove the scrollbar unless it is actually needed.

**Additional context**
![image](https://github.com/oss-slu/Mouser/assets/57450075/d7c5f993-88f5-4443-876f-eca2c3573e20)

**Comment by jackbelyeu** [comment]
Closing this issue since a more modern version of this feat is outlined in #248
