### ISSUE TITLE
Split tests into individual files

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/Mouser#193]
**Describe the feature that you would like added**
Currently, the tests are all in one file, and it looks cluttered. They should be split up into separate files instead.

**Tasks that need to completed for this feature**
- [ ] For each class in the "tests" folder, create an individual file and move it to that file.
- [ ] If necessary, create a separate folder within the "tests" folder for each category that is being tested (such as "databases")
- [ ] Confirm that Pytest still passes

**Comment by jackbelyeu** [comment]
Closing bc tests folder is severely deprecated, test folder should really be a new issue as an overhaul
