### ISSUE TITLE
Restyle/reorganize "create experiment" pages

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/Mouser#194]
**Describe the feature that you would like added**
The pages for the "create experiment" functionality do not look very great. This should be changed to have a nicer styling.

**Tasks that need to completed for this feature**
- new_experiment_ui.py
  - [ ] Remove the "Back to Menu" button
  - [ ] Bring the "+" buttons for the investigators and measurement items closer to their respective textboxes
  - [ ] Add a note that the "password" field is optional
  - [ ] Disable the "Next" button until all required fields are filled out
- group_config_ui.py
  - [ ] Move this file from "experiment" to "create_experiment"
  - [ ] Rename the "Back to Menu" button to "Previous"
  - [ ] Disable the "Next" button until all required fields are filled out
- summary_ui.py
  - [ ] Rename the "Back to Menu" button to "Previous"
- All files
  - [ ] Remove the scrollbars from view until there is overflow

**Additional context**
![image](https://github.com/oss-slu/Mouser/assets/57450075/0367fc30-9a6c-4f85-89f2-79da3a11c258)

**Comment by jackbelyeu** [comment]
Closing as client and team demands and direction has changed, making this issue too outdated
