### ISSUE TITLE
Restyle the Map RFID page

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/Mouser#197]
**Describe the feature that you would like added**
The Map RFID page is not styled very well, and this should be changed.

**Tasks that need to completed for this feature**
- [ ] Remove the "Animal ID" label and textbox (as these aren't needed anymore), and confirm that none of the code relies on either of them
- [ ] Disable the "Remove Selections(s)" button until one or more items are selected
- [ ] Disable the "Change RFID" button until only one item is selected (should not be enabled if multiple are selected)
- [ ] Add functionality so that the option to change RFID appears when a single item is right clicked (similar to what is already possible with "Remove Selection(s)")
- [ ] Increase the height of the table so that it goes further up

**Additional context**
![image](https://github.com/oss-slu/Mouser/assets/57450075/28310ed5-014c-4774-8518-e81d13c61825)
