### ISSUE TITLE
Change the menu bar to be worded more clearly

### ISSUE THREAD

**Issue by loganwyas** [oss-slu/Mouser#200]
**Describe the feature that you would like added**
In the menu bar, each of the options under "File" are not clear in their functionality, so this should be changed to be more clear.

**Tasks that need to completed for this feature**
- [ ] Change "New" to "New Experiment"
- [ ] Change "Open" to "Open Experiment"
- [ ] Change "Save" to "Save File"

**Comment by TeresaZhang11** [comment]
I would like to take this issue!
